exports.up = async knex => {
  await knex.schema.createTable('categories', table => { table.bigIncrements('id').primary(); table.bigInteger('parent_id').unsigned().nullable(); table.string('name', 120).notNullable(); table.string('slug', 140).notNullable().unique(); table.text('description'); table.string('image_path', 255); table.boolean('active').notNullable().defaultTo(true); table.integer('sort_order').notNullable().defaultTo(0); table.timestamps(true, true); table.foreign('parent_id').references('categories.id').onDelete('SET NULL'); });
  await knex.schema.createTable('brands', table => { table.bigIncrements('id').primary(); table.string('name', 120).notNullable().unique(); table.string('slug', 140).notNullable().unique(); table.string('logo_path', 255); table.text('description'); table.boolean('active').notNullable().defaultTo(true); table.timestamps(true, true); });
  await knex.schema.createTable('suppliers', table => { table.bigIncrements('id').primary(); table.string('name', 160).notNullable(); table.string('contact_name', 160); table.string('phone', 60); table.string('email', 190); table.text('address'); table.text('notes'); table.boolean('active').notNullable().defaultTo(true); table.timestamps(true, true); });
  await knex.schema.createTable('products', table => { table.bigIncrements('id').primary(); table.string('name', 200).notNullable(); table.string('slug', 220).notNullable().unique(); table.string('sku', 100).notNullable().unique(); table.string('barcode', 100).unique(); table.string('model', 150); table.bigInteger('brand_id').unsigned().nullable(); table.bigInteger('category_id').unsigned().nullable(); table.bigInteger('supplier_id').unsigned().nullable(); table.text('description'); table.text('specifications'); table.text('features'); table.enum('condition', ['new', 'used', 'refurbished']).notNullable().defaultTo('new'); table.string('warranty', 120); table.decimal('cost_price', 12, 2).notNullable().defaultTo(0); table.decimal('selling_price', 12, 2).notNullable(); table.decimal('discount_price', 12, 2).nullable(); table.decimal('cash_price', 12, 2).nullable(); table.boolean('installment_available').notNullable().defaultTo(false); table.integer('stock_quantity').notNullable().defaultTo(0); table.integer('low_stock_alert').notNullable().defaultTo(3); table.enum('status', ['draft', 'published', 'archived']).notNullable().defaultTo('draft'); table.boolean('featured').notNullable().defaultTo(false); table.boolean('new_arrival').notNullable().defaultTo(false); table.boolean('best_seller').notNullable().defaultTo(false); table.string('thumbnail_path', 255); table.string('tags', 500); table.string('meta_title', 180); table.text('meta_description'); table.timestamps(true, true); table.foreign('brand_id').references('brands.id').onDelete('SET NULL'); table.foreign('category_id').references('categories.id').onDelete('SET NULL'); table.foreign('supplier_id').references('suppliers.id').onDelete('SET NULL'); table.index(['status', 'featured']); table.index(['category_id', 'brand_id']); });
  await knex.schema.createTable('product_images', table => { table.bigIncrements('id').primary(); table.bigInteger('product_id').unsigned().notNullable().references('products.id').onDelete('CASCADE'); table.string('path', 255).notNullable(); table.string('alt_text', 180); table.boolean('is_thumbnail').notNullable().defaultTo(false); table.integer('sort_order').notNullable().defaultTo(0); table.timestamps(true, true); });
  await knex.schema.createTable('stock_movements', table => { table.bigIncrements('id').primary(); table.bigInteger('product_id').unsigned().notNullable().references('products.id').onDelete('CASCADE'); table.bigInteger('user_id').unsigned().nullable().references('users.id').onDelete('SET NULL'); table.enum('type', ['adjustment', 'sale', 'return', 'restock']).notNullable(); table.integer('quantity').notNullable(); table.integer('balance_after').notNullable(); table.string('reference', 120); table.text('notes'); table.timestamps(true, true); table.index('product_id'); });
  await knex.schema.createTable('product_inquiries', table => { table.bigIncrements('id').primary(); table.bigInteger('product_id').unsigned().nullable().references('products.id').onDelete('SET NULL'); table.string('name', 120).notNullable(); table.string('email', 190).notNullable(); table.string('phone', 60); table.text('message').notNullable(); table.enum('status', ['new', 'contacted', 'closed']).notNullable().defaultTo('new'); table.timestamps(true, true); });
};
exports.down = async knex => { for (const table of ['product_inquiries', 'stock_movements', 'product_images', 'products', 'suppliers', 'brands', 'categories']) await knex.schema.dropTableIfExists(table); };
